"""Remove date column

Revision ID: dcbc15551976
Revises: bad7ed9535f0
Create Date: 2019-06-14 16:41:18.780407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcbc15551976'
down_revision = 'bad7ed9535f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
